listen_port: 8302
wx_Config:
  appid: ""
  secret: ""
mysql_config:
  host: 127.0.0.1:3306
  user: root
  password: "123456"
  db_name: pet
oss:
  accessKeyId: ""
  accessKeySecret: ""
  in_host: ""
  host: ""
  callback_url: ""
  upload_dir: ""
  expire_time: 60
log:
  level: 7